name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.21.0
      - name: Build
        run: zola build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
